[package]
name = "rusty-forkfork"
version = "0.4.0"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/oknozor/rusty-forkfork"
documentation = "https://docs.rs/rusty-forkfork"
keywords = ["testing", "process", "fork"]
categories = ["development-tools::testing"]
edition = "2021"

description = """
Cross-platform library for running Rust tests in sub-processes using a
fork-like interface.
"""

[dependencies]
fnv = "1.0"
quick-error = "1.2"
tempfile = "3.0"
